package ai.grayin.core.retrieval

enum class QueryIntent {
    LOCATION_RECALL,
    SCHEDULE_RECALL,
    FUTURE_BUSYNESS_CHECK,
    PHOTO_RECALL,
    NOTIFICATION_PAYMENT_RECALL,
    APP_USAGE_RECALL,
    GENERAL_MEMORY_RECALL,
    NIGHT_OUT_ROUTE_RECONSTRUCTION,
}

